adbaseURL = 'https://learning-out-loud.vercel.app/'
languageCode = 'en-us'
title = "Silly Goose's Thoughts"
theme = 'paper'
renderer.unsafe= true
relativeURLs = true
canonifyURLs = true
[markup]
  [markup.goldmark]
    [markup.goldmark.extensions]
      [markup.goldmark.extensions.passthrough]
        enable = true
        [markup.goldmark.extensions.passthrough.delimiters]
          block = [['\[', '\]'], ['$$', '$$']]
          inline = [['\(', '\)']]
    [markup.goldmark.parser]
      wrapStandAloneImageWithinParagraph = false
      [markup.goldmark.parser.attribute]
        block = true    
    [markup.goldmark.renderer]
      unsafe = true

[params]
  # color style
  color = 'linen'                           # linen, wheat, gray, light

  # header social icons
  github = 'gaspardthrl'                
  linkedin = 'gaspard-thoral-49538a230/'

  # home page profile
  name = ' '
  bio = """The purpose of this so-called blog is mainly for me to better grasp different concepts. Feel free to read it but be aware that everything is potentially a work-in-progress."""


  # misc
  disableHLJS = true                        # disable highlight.js
  disablePostNavigation = true              # disable post navigation
  monoDarkIcon = true                       # show monochrome dark mode icon
  math = true                               # enable KaTeX math typesetting globally
  localKatex = false                        # use local KaTeX js/css instead of CDN
  graphCommentId = "YOUR_GRAPH_COMMENT_ID"  # use graph comment (disqus alternative)


[params.meta]
  favicon = false
